/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiExpensesRouteImport } from './routes/api/expenses'
import { Route as ApiBalancesRouteImport } from './routes/api/balances'
import { Route as ApiExpensesIdRouteImport } from './routes/api/expenses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesRoute = ApiExpensesRouteImport.update({
  id: '/api/expenses',
  path: '/api/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBalancesRoute = ApiBalancesRouteImport.update({
  id: '/api/balances',
  path: '/api/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesIdRoute = ApiExpensesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExpensesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/balances': typeof ApiBalancesRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/balances': typeof ApiBalancesRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/balances': typeof ApiBalancesRoute
  '/api/expenses': typeof ApiExpensesRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/balances'
    | '/api/expenses'
    | '/api/users'
    | '/api/expenses/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/balances'
    | '/api/expenses'
    | '/api/users'
    | '/api/expenses/$id'
  id:
    | '__root__'
    | '/'
    | '/api/balances'
    | '/api/expenses'
    | '/api/users'
    | '/api/expenses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBalancesRoute: typeof ApiBalancesRoute
  ApiExpensesRoute: typeof ApiExpensesRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses': {
      id: '/api/expenses'
      path: '/api/expenses'
      fullPath: '/api/expenses'
      preLoaderRoute: typeof ApiExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/balances': {
      id: '/api/balances'
      path: '/api/balances'
      fullPath: '/api/balances'
      preLoaderRoute: typeof ApiBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses/$id': {
      id: '/api/expenses/$id'
      path: '/$id'
      fullPath: '/api/expenses/$id'
      preLoaderRoute: typeof ApiExpensesIdRouteImport
      parentRoute: typeof ApiExpensesRoute
    }
  }
}

interface ApiExpensesRouteChildren {
  ApiExpensesIdRoute: typeof ApiExpensesIdRoute
}

const ApiExpensesRouteChildren: ApiExpensesRouteChildren = {
  ApiExpensesIdRoute: ApiExpensesIdRoute,
}

const ApiExpensesRouteWithChildren = ApiExpensesRoute._addFileChildren(
  ApiExpensesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBalancesRoute: ApiBalancesRoute,
  ApiExpensesRoute: ApiExpensesRouteWithChildren,
  ApiUsersRoute: ApiUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
